### ISSUE TITLE
Refactor Makefile

### ISSUE THREAD

**Issue by paulapatience** [bbopt/solar#4]
Hi Sebastien,

Generally Makefiles are in the root of the project, which allows you to type `make` without further changing directories. In addition, some of the Makefile's variables, such as `COMPILATOR`, `COMPILATOR_OPTIONS`, etc., differ from the standard names. This is inconveniencing for users accustomed to `CXX`, `CXXFLAGS`, etc., when overriding the flags on the command line. Finally, I see that the dependencies are manually specified in the Makefile. There is a way to automatically generate them with gcc's `-M*` flags.

If you give me the go-ahead, I can prepare a PR addressing these issues.

**Comment by sebastienledigabel** [comment]
Ok as long as it stays simple. Thanks Paul.
