### ISSUE TITLE
Possibly wrong return code from help

### ISSUE THREAD

**Issue by ragonneau** [bbopt/solar#6]
Hi,

First, thank you very much for this simulator; it is very beneficial for testing DFO methods.

A wrong return code seems to be provided when running the following code.

```bash
./bin/solar -h  # or ./bin/solar -h <pb_id>
echo $?
```

Indeed, the value one is returned. Is it intended or is it a small bug in the simulator?

Cheers,
Tom.

**Comment by sebastienledigabel** [comment]
The "1" that is returned is intended. For me, running the help is not running the simulator, and the return code corresponds to the success of the simulator.
